# Generated by Django 2.1.7 on 2019-05-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='dingtalk_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='钉钉'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='dingtalk_robot',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='钉钉个人机器人'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='wechat_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='微信'),
        ),
    ]
