# Generated by Django 2.1.7 on 2019-05-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0002_auto_20190517_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='昵称'),
        ),
    ]
