# Generated by Django 2.1.7 on 2019-05-19 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('anchor', '0001_initial'),
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单编号')),
                ('order_type', models.IntegerField(blank=True, choices=[(0, '指定单'), (1, '随机单'), (2, '表白单')], default=0, null=True, verbose_name='订单类型')),
                ('renew', models.IntegerField(blank=True, choices=[(0, '首单'), (1, '续单')], default=0, null=True, verbose_name='首续单')),
                ('wechat_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='微信号')),
                ('gender', models.IntegerField(blank=True, choices=[(0, '女'), (1, '男'), (2, '不限')], null=True, verbose_name='性别')),
                ('number', models.IntegerField(default=1, verbose_name='件数')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('origin_amount', models.FloatField(verbose_name='原金额')),
                ('deduction', models.FloatField(default=0, verbose_name='折扣金额')),
                ('total_amount', models.FloatField(verbose_name='总金额')),
                ('rmb_amount', models.FloatField(verbose_name='人民币金额')),
                ('order_time', models.DateTimeField(db_index=True, verbose_name='下单时间')),
                ('pay_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='付款时间')),
                ('complete_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='完成时间')),
                ('salary_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='工资结算时间')),
                ('status', models.IntegerField(choices=[(-1, '付款超时失败'), (0, '已删除'), (1, '待付款'), (2, '待接单'), (3, '待抢单'), (4, '待发放工资'), (5, '正常关闭'), (6, '已换人')], db_index=True, default=1, verbose_name='状态')),
                ('anchor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='anchor.Anchor', verbose_name='店员')),
                ('anchor_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='anchor.AnchorType', verbose_name='店员等级')),
                ('product_anchor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='product.ProductAnchorType', verbose_name='产品')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='user_info.UserInfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('order_history_id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单记录编号')),
                ('date', models.DateField(db_index=True, verbose_name='日期')),
                ('update_date', models.DateTimeField(default=0, verbose_name='更新时间')),
                ('order_number', models.IntegerField(default=0, verbose_name='订单数量')),
                ('order_amount', models.FloatField(default=0, verbose_name='订单金额')),
                ('direct_order_number', models.IntegerField(default=0, verbose_name='指定单数量')),
                ('direct_order_amount', models.FloatField(default=0, verbose_name='指定单金额')),
                ('random_order_number', models.IntegerField(default=0, verbose_name='随机单数量')),
                ('random_order_amount', models.FloatField(default=0, verbose_name='随机单金额')),
                ('first_order_number', models.IntegerField(default=0, verbose_name='首单数量')),
                ('first_order_amount', models.FloatField(default=0, verbose_name='首单金额')),
                ('renew_order_number', models.IntegerField(default=0, verbose_name='续单数量')),
                ('renew_order_amount', models.FloatField(default=0, verbose_name='续单金额')),
                ('complete_number', models.IntegerField(default=0, verbose_name='结单数量')),
                ('complete_amount', models.FloatField(default=0, verbose_name='结单金额')),
                ('salary_number', models.IntegerField(default=0, verbose_name='发工资数量')),
                ('salary_amount', models.FloatField(default=0, verbose_name='发工资金额')),
                ('access_count', models.IntegerField(default=0, verbose_name='访问总量')),
                ('distinct_access_count', models.IntegerField(default=0, verbose_name='访问用户数量')),
            ],
            options={
                'verbose_name': '订单统计',
                'verbose_name_plural': '订单统计',
                'db_table': 'order_history',
            },
        ),
    ]
