# Generated by Django 2.1.7 on 2019-05-15 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_info', '0001_initial'),
        ('anchor', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单编号')),
                ('gender', models.IntegerField(blank=True, choices=[(0, '女'), (1, '男'), (2, '不限')], null=True, verbose_name='性别')),
                ('status', models.IntegerField(choices=[(0, '已删除'), (1, '待付款'), (2, '待接单'), (3, '待抢单'), (4, '待发放工资'), (5, '正常关闭'), (6, '已换人'), (7, '付款超时失败')], default=1, verbose_name='状态')),
                ('number', models.FloatField(default=1, verbose_name='件数')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('origin_amount', models.FloatField(verbose_name='原金额')),
                ('deduction', models.FloatField(default=0, verbose_name='折扣金额')),
                ('total_amount', models.FloatField(verbose_name='总金额')),
                ('rmb_amount', models.FloatField(verbose_name='人民币金额')),
                ('order_time', models.DateTimeField(verbose_name='下单时间')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='付款时间')),
                ('complete_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('salary_time', models.DateTimeField(blank=True, null=True, verbose_name='工资结算时间')),
                ('anchor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anchor', to='anchor.Anchor', verbose_name='雇员')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='product.ProductAnchorType', verbose_name='产品')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='user_info.UserInfo', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
                'db_table': 'order',
            },
        ),
    ]
