# Generated by Django 2.1.7 on 2019-03-22 04:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='product.ProductEmployeeType', verbose_name='产品'),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='employee.Employee', verbose_name='雇员'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 4, 36, 46, 523124, tzinfo=utc), verbose_name='下单时间'),
        ),
    ]
