# Generated by Django 2.1.7 on 2019-05-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='employee_id',
            new_name='anchor_id',
        ),
    ]
