# Generated by Django 2.1.7 on 2019-05-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wechat_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='微信号'),
        ),
    ]
