# Generated by Django 2.1.7 on 2019-05-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(-2, '已换人'), (-1, '付款超时失败'), (0, '已取消'), (1, '待付款'), (2, '待接单'), (3, '待抢单'), (4, '待发放工资'), (5, '已完成')], db_index=True, default=1, verbose_name='状态'),
        ),
    ]
