# Generated by Django 2.1.7 on 2019-05-17 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0002_auto_20190516_1753'),
        ('order', '0002_order_wechat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='anchor_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='random_order', to='anchor.AnchorType', verbose_name='店员等级'),
        ),
        migrations.AlterField(
            model_name='order',
            name='anchor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='anchor.Anchor', verbose_name='雇员'),
        ),
    ]
