# Generated by Django 2.1.7 on 2019-04-09 10:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190322_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 10, 46, 6, 434184, tzinfo=utc), verbose_name='下单时间'),
        ),
    ]
