# Generated by Django 2.1.7 on 2019-05-17 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190518_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='anchor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='anchor.Anchor', verbose_name='店员'),
        ),
    ]
