# Generated by Django 2.1.7 on 2019-05-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190518_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.IntegerField(blank=True, choices=[(0, '指定单'), (1, '随机单'), (2, '表白单')], default=0, null=True, verbose_name='订单类型'),
        ),
        migrations.AddField(
            model_name='order',
            name='renew_order',
            field=models.IntegerField(blank=True, choices=[(0, '首单'), (1, '续单')], default=0, null=True, verbose_name='续单'),
        ),
    ]
