# Generated by Django 2.1.7 on 2019-05-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190518_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('order_history_id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单记录编号')),
                ('date', models.DateField(db_index=True, verbose_name='日期')),
                ('update_date', models.DateTimeField(verbose_name='更新时间')),
                ('order_number', models.IntegerField(verbose_name='订单数量')),
                ('order_amount', models.FloatField(verbose_name='订单金额')),
                ('direct_order_number', models.IntegerField(verbose_name='指定单数量')),
                ('direct_order_amount', models.FloatField(verbose_name='指定单金额')),
                ('random_order_number', models.IntegerField(verbose_name='随机单数量')),
                ('random_order_amount', models.FloatField(verbose_name='随机单金额')),
                ('first_order_number', models.IntegerField(verbose_name='首单数量')),
                ('first_order_amount', models.FloatField(verbose_name='首单金额')),
                ('renew_order_number', models.IntegerField(verbose_name='续单数量')),
                ('renew_order_amount', models.FloatField(verbose_name='续单金额')),
                ('complete_number', models.IntegerField(verbose_name='结单数量')),
                ('complete_amount', models.FloatField(verbose_name='结单金额')),
                ('salary_number', models.IntegerField(verbose_name='发工资数量')),
                ('salary_amount', models.FloatField(verbose_name='发工资金额')),
            ],
            options={
                'verbose_name': '订单统计',
                'verbose_name_plural': '订单统计',
                'db_table': 'order_history',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='complete_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(db_index=True, verbose_name='下单时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='付款时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='salary_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='工资结算时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, '已删除'), (1, '待付款'), (2, '待接单'), (3, '待抢单'), (4, '待发放工资'), (5, '正常关闭'), (6, '已换人'), (-1, '付款超时失败')], db_index=True, default=1, verbose_name='状态'),
        ),
    ]
