# Generated by Django 2.1.7 on 2019-05-19 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anchor',
            fields=[
                ('anchor_id', models.AutoField(primary_key=True, serialize=False, verbose_name='店员编号')),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
                ('wechat_id', models.CharField(max_length=30, verbose_name='微信')),
                ('open_id', models.CharField(blank=True, max_length=60, null=True, verbose_name='微信openid')),
                ('gender', models.IntegerField(choices=[(0, '女'), (1, '男'), (2, '不限')], verbose_name='性别')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='城市')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('audio', models.CharField(blank=True, max_length=100, null=True, verbose_name='音频')),
                ('avatar', models.CharField(blank=True, max_length=100, null=True, verbose_name='头像')),
                ('image', models.CharField(blank=True, max_length=300, null=True, verbose_name='图片')),
                ('skill', models.CharField(blank=True, max_length=100, null=True, verbose_name='特长')),
                ('online', models.CharField(blank=True, max_length=100, null=True, verbose_name='在线时间')),
                ('occupation', models.CharField(blank=True, max_length=20, null=True, verbose_name='职业')),
                ('slogan', models.CharField(max_length=150, null=True, verbose_name='标语')),
                ('tags', models.CharField(blank=True, max_length=50, null=True, verbose_name='标签')),
                ('dingtalk_mobile', models.CharField(blank=True, max_length=30, null=True, verbose_name='钉钉绑定手机号')),
                ('dingtalk_robot', models.CharField(blank=True, max_length=100, null=True, verbose_name='钉钉个人机器人')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='入职日期')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='离职日期')),
                ('status', models.IntegerField(choices=[(0, '离职'), (1, '在职')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '店员信息',
                'verbose_name_plural': '店员信息',
                'db_table': 'anchor',
            },
        ),
        migrations.CreateModel(
            name='AnchorApplyRecord',
            fields=[
                ('anchor_apply_record_id', models.AutoField(primary_key=True, serialize=False, verbose_name='申请编号')),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
                ('wechat_id', models.CharField(max_length=30, verbose_name='微信')),
                ('open_id', models.CharField(blank=True, max_length=60, null=True, verbose_name='微信openid')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='城市')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('gender', models.IntegerField(choices=[(0, '女'), (1, '男'), (2, '不限')], verbose_name='性别')),
                ('audio', models.CharField(blank=True, max_length=100, null=True, verbose_name='音频')),
                ('avatar', models.CharField(blank=True, max_length=100, null=True, verbose_name='头像')),
                ('image', models.CharField(blank=True, max_length=300, null=True, verbose_name='图片')),
                ('slogan', models.CharField(max_length=150, null=True, verbose_name='标语')),
                ('tags', models.CharField(blank=True, max_length=50, null=True, verbose_name='标签')),
                ('skill', models.CharField(blank=True, max_length=100, null=True, verbose_name='特长')),
                ('experience', models.BooleanField(default=False, verbose_name='经验')),
                ('occupation', models.CharField(blank=True, max_length=20, null=True, verbose_name='职业')),
                ('online', models.CharField(blank=True, max_length=100, null=True, verbose_name='在线时间')),
                ('status', models.IntegerField(choices=[(1, '待审核'), (2, '审核通过'), (3, '审核失败')], default=1, verbose_name='申请状态')),
                ('apply_date', models.DateField(blank=True, null=True, verbose_name='申请时间')),
                ('audit_date', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditor', to='platform_admin.AdminUser', verbose_name='审核人')),
            ],
            options={
                'verbose_name': '店员申请记录',
                'verbose_name_plural': '店员申请记录',
                'db_table': 'anchor_apply_record',
            },
        ),
        migrations.CreateModel(
            name='AnchorGroup',
            fields=[
                ('anchor_group_id', models.AutoField(primary_key=True, serialize=False, verbose_name='店员钉钉群编号')),
                ('name', models.CharField(max_length=20, verbose_name='店员群名称')),
                ('dingtalk_robot', models.CharField(blank=True, max_length=100, null=True, verbose_name='群钉钉机器人')),
                ('gender', models.IntegerField(choices=[(0, '女'), (1, '男'), (2, '不限')], default=2, verbose_name='性别')),
                ('status', models.BooleanField(choices=[(False, '失效'), (True, '激活')], default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '店员群信息',
                'verbose_name_plural': '店员群信息',
                'db_table': 'anchor_group',
            },
        ),
        migrations.CreateModel(
            name='AnchorTag',
            fields=[
                ('anchor_tag_id', models.AutoField(primary_key=True, serialize=False, verbose_name='标签编号')),
                ('name', models.CharField(max_length=15, verbose_name='标签')),
                ('status', models.BooleanField(choices=[(False, '失效'), (True, '激活')], default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '店员标签信息',
                'verbose_name_plural': '店员标签信息',
                'db_table': 'anchor_tag',
            },
        ),
        migrations.CreateModel(
            name='AnchorType',
            fields=[
                ('anchor_type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='店员类型编号')),
                ('name', models.CharField(max_length=15, verbose_name='店员类型')),
                ('status', models.BooleanField(choices=[(False, '失效'), (True, '激活')], default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '店员类型信息',
                'verbose_name_plural': '店员类型信息',
                'db_table': 'anchor_type',
            },
        ),
        migrations.AddField(
            model_name='anchor',
            name='anchor_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anchors', to='anchor.AnchorType', verbose_name='等级'),
        ),
    ]
