# Generated by Django 2.1.7 on 2019-05-15 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anchor',
            fields=[
                ('anchor_id', models.AutoField(primary_key=True, serialize=False, verbose_name='店员编号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
                ('status', models.IntegerField(choices=[(0, '离职'), (1, '在职'), (2, '待审核'), (3, '审核未通过')], default=2, verbose_name='状态')),
                ('identity_type', models.IntegerField(choices=[(0, '身份证'), (1, '护照'), (2, '驾驶证')], default=0, verbose_name='证件类型')),
                ('identity', models.CharField(max_length=20, verbose_name='证件号码')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('gender', models.IntegerField(choices=[(0, '女'), (1, '男'), (2, '混合')], verbose_name='性别')),
                ('mobile', models.CharField(max_length=20, verbose_name='联系电话')),
                ('dingtalk_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='钉钉')),
                ('dingtalk_robot', models.CharField(blank=True, max_length=100, null=True, verbose_name='钉钉个人机器人')),
                ('wechat_id', models.CharField(max_length=30, verbose_name='微信')),
                ('audio', models.CharField(blank=True, max_length=100, null=True, verbose_name='音频')),
                ('avatar', models.CharField(blank=True, max_length=100, null=True, verbose_name='头像')),
                ('img1', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片1')),
                ('img2', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片2')),
                ('img3', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片3')),
                ('audit_date', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='入职日期')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='离职日期')),
                ('slogan', models.CharField(max_length=150, null=True, verbose_name='标语')),
                ('tags', models.CharField(blank=True, max_length=50, null=True, verbose_name='标签')),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditor', to='platform_admin.AdminUser', verbose_name='审核人')),
            ],
            options={
                'verbose_name': '店员信息',
                'verbose_name_plural': '店员信息',
                'db_table': 'anchor',
            },
        ),
        migrations.CreateModel(
            name='AnchorCity',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False, verbose_name='城市编号')),
                ('name', models.CharField(max_length=15, verbose_name='中文名')),
                ('en_name', models.CharField(blank=True, max_length=15, null=True, verbose_name='英文名')),
                ('status', models.BooleanField(choices=[(False, '失效'), (True, '激活')], default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '店员城市信息',
                'verbose_name_plural': '店员城市信息',
                'db_table': 'anchor_city',
            },
        ),
        migrations.CreateModel(
            name='AnchorGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False, verbose_name='店员钉钉群编号')),
                ('name', models.CharField(max_length=20, verbose_name='群名称')),
                ('dingding_id', models.CharField(max_length=30, verbose_name='钉钉id')),
                ('gender', models.IntegerField(choices=[(0, '女'), (1, '男'), (2, '混合')], default=2, verbose_name='性别')),
                ('status', models.BooleanField(choices=[(False, '失效'), (True, '激活')], default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '店员群信息',
                'verbose_name_plural': '店员群信息',
                'db_table': 'anchor_group',
            },
        ),
        migrations.CreateModel(
            name='AnchorTag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False, verbose_name='标签编号')),
                ('name', models.CharField(max_length=15, verbose_name='标签')),
                ('status', models.BooleanField(choices=[(False, '失效'), (True, '激活')], default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '店员标签信息',
                'verbose_name_plural': '店员标签信息',
                'db_table': 'anchor_tag',
            },
        ),
        migrations.CreateModel(
            name='AnchorType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='店员类型编号')),
                ('name', models.CharField(max_length=15, verbose_name='店员类型')),
                ('status', models.BooleanField(choices=[(False, '失效'), (True, '激活')], default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '店员类型信息',
                'verbose_name_plural': '店员类型信息',
                'db_table': 'anchor_type',
            },
        ),
        migrations.AddField(
            model_name='anchor',
            name='city_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city', to='anchor.AnchorCity', verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='anchor',
            name='type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type', to='anchor.AnchorType', verbose_name='等级'),
        ),
    ]
