# Generated by Django 2.1.7 on 2019-05-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchor',
            name='open_id',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='微信openid'),
        ),
        migrations.AddField(
            model_name='anchorapplyrecord',
            name='open_id',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='微信openid'),
        ),
    ]
