# Generated by Django 2.1.7 on 2019-05-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anchor',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='anchor',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='anchor',
            name='img3',
        ),
        migrations.AddField(
            model_name='anchor',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='图片'),
        ),
    ]
