# Generated by Django 2.1.7 on 2019-05-15 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0001_initial'),
        ('anchor', '0002_auto_20190515_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnchorApplyRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False, verbose_name='申请编号')),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='城市')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('gender', models.IntegerField(choices=[(0, '女'), (1, '男'), (2, '混合')], verbose_name='性别')),
                ('wechat_id', models.CharField(max_length=30, verbose_name='微信')),
                ('audio', models.CharField(blank=True, max_length=100, null=True, verbose_name='音频')),
                ('avatar', models.CharField(blank=True, max_length=100, null=True, verbose_name='头像')),
                ('image', models.CharField(blank=True, max_length=300, null=True, verbose_name='图片')),
                ('slogan', models.CharField(max_length=150, null=True, verbose_name='标语')),
                ('tags', models.CharField(blank=True, max_length=50, null=True, verbose_name='标签')),
                ('skill', models.CharField(blank=True, max_length=100, null=True, verbose_name='特长')),
                ('experience', models.BooleanField(default=False, verbose_name='经验')),
                ('occupation', models.CharField(blank=True, max_length=20, null=True, verbose_name='职业')),
                ('online', models.CharField(blank=True, max_length=100, null=True, verbose_name='特长')),
                ('status', models.IntegerField(choices=[(1, '待审核'), (2, '审核通过'), (3, '审核失败')], default=1, verbose_name='状态')),
                ('apply_date', models.DateField(blank=True, null=True, verbose_name='申请时间')),
                ('audit_date', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditor', to='platform_admin.AdminUser', verbose_name='审核人')),
            ],
            options={
                'verbose_name': '店员申请记录',
                'verbose_name_plural': '店员申请记录',
                'db_table': 'anchor_apply_record',
            },
        ),
        migrations.RemoveField(
            model_name='anchor',
            name='audit_date',
        ),
        migrations.RemoveField(
            model_name='anchor',
            name='auditor',
        ),
        migrations.RemoveField(
            model_name='anchor',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='anchor',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='anchor',
            name='identity_type',
        ),
        migrations.RemoveField(
            model_name='anchor',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='anchor',
            name='name',
        ),
        migrations.AddField(
            model_name='anchor',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='anchor',
            name='occupation',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='职业'),
        ),
        migrations.AddField(
            model_name='anchor',
            name='online',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='特长'),
        ),
        migrations.AddField(
            model_name='anchor',
            name='skill',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='特长'),
        ),
        migrations.AlterField(
            model_name='anchor',
            name='status',
            field=models.IntegerField(choices=[(0, '离职'), (1, '在职')], default=2, verbose_name='状态'),
        ),
        migrations.DeleteModel(
            name='AnchorCity',
        ),
    ]
