# Generated by Django 2.1.7 on 2019-05-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0002_auto_20190516_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchorgroup',
            name='dingtalk_robot',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='钉钉机器人'),
        ),
        migrations.AlterField(
            model_name='anchorgroup',
            name='dingding_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='钉钉id'),
        ),
    ]
