# Generated by Django 2.1.7 on 2019-05-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0003_auto_20190516_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchor',
            name='online',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='在线时间'),
        ),
        migrations.AlterField(
            model_name='anchor',
            name='status',
            field=models.IntegerField(choices=[(0, '离职'), (1, '在职')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='anchorapplyrecord',
            name='online',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='在线时间'),
        ),
    ]
