# Generated by Django 2.1.7 on 2019-05-17 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0003_auto_20190518_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anchorgroup',
            old_name='dingding_id',
            new_name='dingtalk_id',
        ),
    ]
