# Generated by Django 2.1.7 on 2019-05-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0004_auto_20190518_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anchorgroup',
            name='dingtalk_id',
        ),
    ]
