# Generated by Django 2.1.7 on 2019-05-15 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anchor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False, verbose_name='产品编号')),
                ('name', models.CharField(max_length=20, verbose_name='产品名称')),
                ('eng_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='产品英文名称')),
                ('time', models.FloatField(default=1, verbose_name='时长')),
                ('partition', models.FloatField(default=0.5, verbose_name='首单分成')),
                ('partition_extend', models.FloatField(default=0.6, verbose_name='续单分成')),
                ('status', models.BooleanField(choices=[(False, '失效'), (True, '激活')], default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '产品信息',
                'verbose_name_plural': '产品信息',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductAnchorType',
            fields=[
                ('product_anchor_type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='产品-店员类型编号')),
                ('price', models.FloatField(verbose_name='价格')),
                ('status', models.BooleanField(choices=[(False, '失效'), (True, '激活')], default=True, verbose_name='状态')),
                ('anchor_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anchor_type', to='anchor.AnchorType', verbose_name='店员类型')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.Product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品-店员类型',
                'verbose_name_plural': '产品-店员类型',
                'db_table': 'product_anchor_type',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='产品类型编号')),
                ('name', models.CharField(max_length=20, verbose_name='产品类型名称')),
                ('eng_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='产品类型英文名称')),
                ('status', models.BooleanField(choices=[(False, '失效'), (True, '激活')], default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '产品类型信息',
                'verbose_name_plural': '产品类型信息',
                'db_table': 'product_type',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='product.ProductType', verbose_name='产品类型'),
        ),
    ]
