# Generated by Django 2.1.7 on 2019-05-19 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '产品-时长信息', 'verbose_name_plural': '产品-时长信息'},
        ),
        migrations.AlterModelOptions(
            name='productanchortype',
            options={'verbose_name': '产品-时长-店员类型', 'verbose_name_plural': '产品-时长-店员类型'},
        ),
    ]
