# Generated by Django 2.2 on 2019-05-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(choices=[(False, '失效'), (True, '激活')], default=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='productemployeetype',
            name='status',
            field=models.BooleanField(choices=[(False, '失效'), (True, '激活')], default=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='status',
            field=models.BooleanField(choices=[(False, '失效'), (True, '激活')], default=True, verbose_name='状态'),
        ),
    ]
