# Generated by Django 2.1.7 on 2019-05-15 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productanchortype',
            name='anchor_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='anchor.AnchorType', verbose_name='店员类型'),
        ),
        migrations.AlterField(
            model_name='productanchortype',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anchor_type', to='product.Product', verbose_name='产品'),
        ),
    ]
