# Generated by Django 2.1.7 on 2019-05-15 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户编号')),
                ('open_id', models.CharField(blank=True, max_length=60, null=True, verbose_name='微信开放编号')),
                ('nickname', models.CharField(blank=True, max_length=20, null=True, verbose_name='用户昵称')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后登入时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='UserLoginInfo',
            fields=[
                ('user_login_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户登入编号')),
                ('time', models.DateTimeField(verbose_name='时间')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_user_id', to='user_info.UserInfo', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '用户登陆日志',
                'verbose_name_plural': '用户登陆日志',
                'db_table': 'user_login_info',
            },
        ),
    ]
