# Generated by Django 2.1.7 on 2019-05-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='用户头像'),
        ),
    ]
