# Generated by Django 2.1.7 on 2019-05-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='access_token',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Token'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.IntegerField(default=0, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='headimgurl',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='用户头像'),
        ),
    ]
