# Generated by Django 2.1.7 on 2019-05-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0002_auto_20190516_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='headimgurl',
            new_name='avatar',
        ),
    ]
