# Generated by Django 2.1.7 on 2019-05-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0002_auto_20190523_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='用户昵称'),
        ),
    ]
