# Generated by Django 2.1.7 on 2019-04-09 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0002_userlogininfo_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogininfo',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_user_id', to='user_info.UserInfo', verbose_name='用户id'),
        ),
    ]
