# Generated by Django 2.1.7 on 2019-05-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0003_auto_20190516_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.IntegerField(choices=[(0, '女'), (1, '男'), (2, '不限')], default=0, verbose_name='性别'),
        ),
    ]
