# Generated by Django 2.1.7 on 2019-03-22 00:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False, verbose_name='雇员编号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
                ('status', models.IntegerField(choices=[(0, '离职'), (1, '在职'), (2, '待审')], default=2, verbose_name='状态')),
                ('identity_type', models.IntegerField(choices=[(0, '身份证'), (1, '护照'), (2, '驾驶证')], default=0, verbose_name='证件类型')),
                ('identity', models.CharField(max_length=20, verbose_name='证件号码')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')], verbose_name='性别')),
                ('mobile', models.CharField(max_length=20, verbose_name='联系电话')),
                ('dingtalk_id', models.CharField(max_length=30, null=True, verbose_name='钉钉')),
                ('wechat_id', models.CharField(max_length=30, verbose_name='微信')),
                ('audio', models.CharField(max_length=100, verbose_name='音频')),
                ('avatar', models.CharField(blank=True, max_length=100, null=True, verbose_name='头像')),
                ('img1', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片1')),
                ('img2', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片2')),
                ('img3', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片3')),
                ('join_date', models.DateField(default=datetime.date(2019, 3, 22), verbose_name='入职日期')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='离职日期')),
                ('slogan', models.CharField(max_length=150, null=True, verbose_name='标语')),
            ],
            options={
                'verbose_name': '雇员信息',
                'verbose_name_plural': '雇员信息',
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='EmployeeCity',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False, verbose_name='城市编号')),
                ('name', models.CharField(max_length=15, verbose_name='中文名')),
                ('en_name', models.CharField(blank=True, max_length=15, null=True, verbose_name='英文名')),
                ('status', models.BooleanField(choices=[(False, '停用'), (True, '激活')], default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '雇员城市',
                'verbose_name_plural': '雇员城市',
                'db_table': 'employee_city',
            },
        ),
        migrations.CreateModel(
            name='EmployeeGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False, verbose_name='雇员钉钉群编号')),
                ('name', models.CharField(max_length=20, verbose_name='群名称')),
                ('dingding_id', models.CharField(max_length=30, verbose_name='钉钉id')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女'), (2, '混合')], default=2, verbose_name='性别')),
                ('status', models.IntegerField(choices=[(0, '停用'), (1, '激活')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '雇员群信息',
                'verbose_name_plural': '雇员群信息',
                'db_table': 'employee_group',
            },
        ),
        migrations.CreateModel(
            name='EmployeeTag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False, verbose_name='标签编号')),
                ('name', models.CharField(max_length=15, verbose_name='标签')),
                ('status', models.BooleanField(choices=[(False, '停用'), (True, '激活')], default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '雇员标签',
                'verbose_name_plural': '雇员标签',
                'db_table': 'employee_tag',
            },
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='雇员类型编号')),
                ('name', models.CharField(max_length=15, verbose_name='雇员类型')),
                ('status', models.IntegerField(choices=[(0, '停用'), (1, '激活')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '雇员类型信息',
                'verbose_name_plural': '雇员类型信息',
                'db_table': 'employee_type',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='city_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city', to='employee.EmployeeCity', verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='employee',
            name='type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type', to='employee.EmployeeType', verbose_name='等级'),
        ),
    ]
