# Generated by Django 2.1.7 on 2019-03-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeecity',
            options={'verbose_name': '雇员城市信息', 'verbose_name_plural': '雇员城市信息'},
        ),
        migrations.AlterModelOptions(
            name='employeetag',
            options={'verbose_name': '雇员标签信息', 'verbose_name_plural': '雇员标签信息'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='audio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='音频'),
        ),
    ]
