# Generated by Django 2.1.7 on 2019-03-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20190322_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tags',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.DateField(blank=True, null=True, verbose_name='入职日期'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.IntegerField(choices=[(0, '离职'), (1, '在职'), (2, '待审'), (3, '审核失败')], default=2, verbose_name='状态'),
        ),
    ]
