# Generated by Django 2.1.7 on 2019-05-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20190511_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='audit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
    ]
