# Generated by Django 2.1.7 on 2019-05-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_audit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dingtalk_robot',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='钉钉个人机器人'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dingtalk_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='钉钉'),
        ),
    ]
