# Generated by Django 2.1.7 on 2019-05-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformInfo',
            fields=[
                ('platform_info_id', models.AutoField(primary_key=True, serialize=False, verbose_name='平台信息编号')),
                ('tag', models.CharField(max_length=20, verbose_name='标签')),
                ('tag_cn', models.CharField(max_length=40, verbose_name='描述')),
                ('content', models.TextField(max_length=500, verbose_name='内容')),
                ('status', models.BooleanField(choices=[(False, '失效'), (True, '激活')], default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '平台信息',
                'verbose_name_plural': '平台信息',
                'db_table': 'platform_info',
            },
        ),
    ]
